# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2020.6.20-hecda079_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2020.2-254.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.33.1-h53a641e_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandoc-2.10.1-0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2020.2-256.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libsodium-1.0.18-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_1.conda
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1h-h516909a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20191231-h14c3975_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.0-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.10-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zeromq-4.3.2-he6710b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.33.0-h62c20be_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.7.9-h7579374_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/async_generator-1.10-py37h28b3542_0.conda
https://repo.anaconda.com/pkgs/main/noarch/attrs-20.2.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-4.4.2-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.6.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/entrypoints-0.3-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython_genutils-0.2.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lazy-object-proxy-1.4.3-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-1.1.1-py37h14c3975_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mccabe-0.6.1-py37_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mistune-0.8.4-py37h14c3975_1001.conda
https://repo.anaconda.com/pkgs/main/noarch/nest-asyncio-1.4.1-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandocfilters-1.4.2-py37_1.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.7.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pickleshare-0.7.5-py37_1001.conda
https://repo.anaconda.com/pkgs/main/noarch/prometheus_client-0.8.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ptyprocess-0.6.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.20-py_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyrsistent-0.17.3-py37h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.7-1_cp37m.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-19.0.2-py37he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/send2trash-1.5.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.15.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/testpath-0.4.4-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toml-0.10.1-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.0.4-py37h7b6447c_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/typed-ast-1.4.1-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/webencodings-0.5.1-py37_1.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.35.1-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wrapt-1.11.2-py37h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/zipp-3.3.0-py_0.conda
https://conda.anaconda.org/conda-forge/linux-64/certifi-2020.6.20-py37he5f6b98_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.14.3-py37he30daa8_0.conda
https://repo.anaconda.com/pkgs/main/noarch/importlib-metadata-2.0.0-py_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.17.2-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.3.0-py37he904b0f_0.conda
https://repo.anaconda.com/pkgs/main/noarch/packaging-20.4-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pexpect-4.8.0-py37_1.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/terminado-0.9.1-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/traitlets-5.0.4-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/argon2-cffi-20.1.0-py37h7b6447c_1.conda
https://repo.anaconda.com/pkgs/main/noarch/importlib_metadata-2.0.0-1.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_core-4.6.3-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.19.1-py37hfa32c7d_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-49.6.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/astroid-2.4.2-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/bleach-3.2.1-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/isort-5.5.3-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jinja2-2.11.2-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jsonschema-3.2.0-py37_1.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyter_client-6.1.7-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-20.2.2-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.7.1-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_pygments-0.1.2-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/nbformat-5.0.7-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt-toolkit-3.0.7-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pylint-2.6.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython-7.18.1-py37h5ca1d4c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/nbclient-0.5.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-5.3.4-py37h5ca1d4c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nbconvert-6.0.7-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/notebook-6.1.4-py37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/widgetsnbextension-3.5.1-py37_0.conda
https://conda.anaconda.org/conda-forge/noarch/ipywidgets-7.5.1-pyh9f0ad1d_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.2.0-py37h23d657b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.1.1-py37h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.19.1-py37hbc911f0_0.conda
